/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IInterchainTransferSent,
  IInterchainTransferSentInterface,
} from "../../../../../axelar-gmp-sdk-solidity/contracts/interfaces/IInterchainTransfer.sol/IInterchainTransferSent";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "destinationChain",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "destinationContractAddress",
        type: "string",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "recipient",
        type: "bytes",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "InterchainTransferSent",
    type: "event",
  },
] as const;

export class IInterchainTransferSent__factory {
  static readonly abi = _abi;
  static createInterface(): IInterchainTransferSentInterface {
    return new utils.Interface(_abi) as IInterchainTransferSentInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInterchainTransferSent {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IInterchainTransferSent;
  }
}
