/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AxelarDepositService } from "./AxelarDepositService";
export type { AxelarDepositServiceProxy } from "./AxelarDepositServiceProxy";
export type { DepositReceiver } from "./DepositReceiver";
export type { DepositServiceBase } from "./DepositServiceBase";
export type { ReceiverImplementation } from "./ReceiverImplementation";
