/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface ReceiverImplementationInterface extends utils.Interface {
  functions: {
    "gateway()": FunctionFragment;
    "receiveAndSendNative(address,string,string)": FunctionFragment;
    "receiveAndSendToken(address,string,string,string)": FunctionFragment;
    "receiveAndUnwrapNative(address,address)": FunctionFragment;
    "wrappedSymbol()": FunctionFragment;
    "wrappedToken()": FunctionFragment;
    "wrappedTokenAddress()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "gateway"
      | "receiveAndSendNative"
      | "receiveAndSendToken"
      | "receiveAndUnwrapNative"
      | "wrappedSymbol"
      | "wrappedToken"
      | "wrappedTokenAddress"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "gateway", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiveAndSendNative",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveAndSendToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveAndUnwrapNative",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "wrappedSymbol",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "wrappedToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "wrappedTokenAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "gateway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveAndSendNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveAndSendToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveAndUnwrapNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrappedSymbol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrappedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrappedTokenAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ReceiverImplementation extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ReceiverImplementationInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    gateway(overrides?: CallOverrides): Promise<[string]>;

    receiveAndSendNative(
      refundAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    receiveAndSendToken(
      refundAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    receiveAndUnwrapNative(
      refundAddress: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    wrappedSymbol(overrides?: CallOverrides): Promise<[string]>;

    wrappedToken(overrides?: CallOverrides): Promise<[string]>;

    wrappedTokenAddress(overrides?: CallOverrides): Promise<[string]>;
  };

  gateway(overrides?: CallOverrides): Promise<string>;

  receiveAndSendNative(
    refundAddress: PromiseOrValue<string>,
    destinationChain: PromiseOrValue<string>,
    destinationAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  receiveAndSendToken(
    refundAddress: PromiseOrValue<string>,
    destinationChain: PromiseOrValue<string>,
    destinationAddress: PromiseOrValue<string>,
    symbol: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  receiveAndUnwrapNative(
    refundAddress: PromiseOrValue<string>,
    recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  wrappedSymbol(overrides?: CallOverrides): Promise<string>;

  wrappedToken(overrides?: CallOverrides): Promise<string>;

  wrappedTokenAddress(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    gateway(overrides?: CallOverrides): Promise<string>;

    receiveAndSendNative(
      refundAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    receiveAndSendToken(
      refundAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    receiveAndUnwrapNative(
      refundAddress: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    wrappedSymbol(overrides?: CallOverrides): Promise<string>;

    wrappedToken(overrides?: CallOverrides): Promise<string>;

    wrappedTokenAddress(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    gateway(overrides?: CallOverrides): Promise<BigNumber>;

    receiveAndSendNative(
      refundAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    receiveAndSendToken(
      refundAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    receiveAndUnwrapNative(
      refundAddress: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    wrappedSymbol(overrides?: CallOverrides): Promise<BigNumber>;

    wrappedToken(overrides?: CallOverrides): Promise<BigNumber>;

    wrappedTokenAddress(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    gateway(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    receiveAndSendNative(
      refundAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    receiveAndSendToken(
      refundAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    receiveAndUnwrapNative(
      refundAddress: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    wrappedSymbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wrappedToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wrappedTokenAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
