/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface InterchainTokenServiceInterface extends utils.Interface {
  functions: {
    "acceptOperatorship(address)": FunctionFragment;
    "acceptOwnership()": FunctionFragment;
    "chainName()": FunctionFragment;
    "chainNameHash()": FunctionFragment;
    "contractCallValue(string,string,bytes)": FunctionFragment;
    "contractId()": FunctionFragment;
    "deployInterchainToken(bytes32,string,string,string,uint8,bytes,uint256)": FunctionFragment;
    "deployedTokenManager(bytes32)": FunctionFragment;
    "execute(bytes32,string,string,bytes)": FunctionFragment;
    "expressExecute(bytes32,string,string,bytes)": FunctionFragment;
    "gasService()": FunctionFragment;
    "gateway()": FunctionFragment;
    "gatewayCaller()": FunctionFragment;
    "getExpressExecutor(bytes32,string,string,bytes32)": FunctionFragment;
    "hasRole(address,uint8)": FunctionFragment;
    "implementation()": FunctionFragment;
    "interchainTokenAddress(bytes32)": FunctionFragment;
    "interchainTokenDeployer()": FunctionFragment;
    "interchainTokenFactory()": FunctionFragment;
    "interchainTokenId(address,bytes32)": FunctionFragment;
    "interchainTransfer(bytes32,string,bytes,uint256,bytes,uint256)": FunctionFragment;
    "isOperator(address)": FunctionFragment;
    "isTrustedAddress(string,string)": FunctionFragment;
    "linkToken(bytes32,string,bytes,uint8,bytes,uint256)": FunctionFragment;
    "migrateInterchainToken(bytes32)": FunctionFragment;
    "multicall(bytes[])": FunctionFragment;
    "owner()": FunctionFragment;
    "paused()": FunctionFragment;
    "pendingOwner()": FunctionFragment;
    "proposeOperatorship(address)": FunctionFragment;
    "proposeOwnership(address)": FunctionFragment;
    "registerCustomToken(bytes32,address,uint8,bytes)": FunctionFragment;
    "registerTokenMetadata(address,uint256)": FunctionFragment;
    "registeredTokenAddress(bytes32)": FunctionFragment;
    "removeTrustedAddress(string)": FunctionFragment;
    "setFlowLimits(bytes32[],uint256[])": FunctionFragment;
    "setPauseStatus(bool)": FunctionFragment;
    "setTrustedAddress(string,string)": FunctionFragment;
    "setup(bytes)": FunctionFragment;
    "tokenHandler()": FunctionFragment;
    "tokenManager()": FunctionFragment;
    "tokenManagerAddress(bytes32)": FunctionFragment;
    "tokenManagerDeployer()": FunctionFragment;
    "tokenManagerImplementation(uint256)": FunctionFragment;
    "transferOperatorship(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transmitInterchainTransfer(bytes32,address,string,bytes,uint256,bytes)": FunctionFragment;
    "trustedAddress(string)": FunctionFragment;
    "trustedAddressHash(string)": FunctionFragment;
    "upgrade(address,bytes32,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptOperatorship"
      | "acceptOwnership"
      | "chainName"
      | "chainNameHash"
      | "contractCallValue"
      | "contractId"
      | "deployInterchainToken"
      | "deployedTokenManager"
      | "execute"
      | "expressExecute"
      | "gasService"
      | "gateway"
      | "gatewayCaller"
      | "getExpressExecutor"
      | "hasRole"
      | "implementation"
      | "interchainTokenAddress"
      | "interchainTokenDeployer"
      | "interchainTokenFactory"
      | "interchainTokenId"
      | "interchainTransfer"
      | "isOperator"
      | "isTrustedAddress"
      | "linkToken"
      | "migrateInterchainToken"
      | "multicall"
      | "owner"
      | "paused"
      | "pendingOwner"
      | "proposeOperatorship"
      | "proposeOwnership"
      | "registerCustomToken"
      | "registerTokenMetadata"
      | "registeredTokenAddress"
      | "removeTrustedAddress"
      | "setFlowLimits"
      | "setPauseStatus"
      | "setTrustedAddress"
      | "setup"
      | "tokenHandler"
      | "tokenManager"
      | "tokenManagerAddress"
      | "tokenManagerDeployer"
      | "tokenManagerImplementation"
      | "transferOperatorship"
      | "transferOwnership"
      | "transmitInterchainTransfer"
      | "trustedAddress"
      | "trustedAddressHash"
      | "upgrade"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptOperatorship",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "chainName", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "chainNameHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contractCallValue",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "contractId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployInterchainToken",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedTokenManager",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "expressExecute",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "gasService",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gateway", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "gatewayCaller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExpressExecutor",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "interchainTokenAddress",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "interchainTokenDeployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "interchainTokenFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "interchainTokenId",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "interchainTransfer",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedAddress",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "linkToken",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "migrateInterchainToken",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposeOperatorship",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCustomToken",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerTokenMetadata",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredTokenAddress",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeTrustedAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFlowLimits",
    values: [PromiseOrValue<BytesLike>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setPauseStatus",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedAddress",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setup",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenHandler",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenManagerAddress",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenManagerDeployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenManagerImplementation",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOperatorship",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transmitInterchainTransfer",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedAddressHash",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOperatorship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chainName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chainNameHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractCallValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contractId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployInterchainToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedTokenManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "expressExecute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasService", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gateway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gatewayCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpressExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interchainTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interchainTokenDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interchainTokenFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interchainTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interchainTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOperator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "linkToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "migrateInterchainToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeOperatorship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCustomToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerTokenMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeTrustedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFlowLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPauseStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenManagerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenManagerDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenManagerImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOperatorship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transmitInterchainTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedAddressHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;

  events: {
    "ExpressExecuted(bytes32,string,string,bytes32,address)": EventFragment;
    "ExpressExecutionFulfilled(bytes32,string,string,bytes32,address)": EventFragment;
    "InterchainTokenDeployed(bytes32,address,address,string,string,uint8)": EventFragment;
    "InterchainTokenDeploymentStarted(bytes32,string,string,uint8,bytes,string)": EventFragment;
    "InterchainTokenIdClaimed(bytes32,address,bytes32)": EventFragment;
    "InterchainTransfer(bytes32,address,string,bytes,uint256,bytes32)": EventFragment;
    "InterchainTransferReceived(bytes32,bytes32,string,bytes,address,uint256,bytes32)": EventFragment;
    "LinkTokenStarted(bytes32,string,bytes,bytes,uint8,bytes)": EventFragment;
    "OwnershipTransferStarted(address)": EventFragment;
    "OwnershipTransferred(address)": EventFragment;
    "Paused(address)": EventFragment;
    "RolesAdded(address,uint256)": EventFragment;
    "RolesProposed(address,address,uint256)": EventFragment;
    "RolesRemoved(address,uint256)": EventFragment;
    "TokenManagerDeployed(bytes32,address,uint8,bytes)": EventFragment;
    "TokenMetadataRegistered(address,uint8)": EventFragment;
    "TrustedAddressRemoved(string)": EventFragment;
    "TrustedAddressSet(string,string)": EventFragment;
    "Unpaused(address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ExpressExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExpressExecutionFulfilled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InterchainTokenDeployed"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "InterchainTokenDeploymentStarted"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InterchainTokenIdClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InterchainTransfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InterchainTransferReceived"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LinkTokenStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RolesAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RolesProposed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RolesRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenManagerDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenMetadataRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TrustedAddressRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TrustedAddressSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface ExpressExecutedEventObject {
  commandId: string;
  sourceChain: string;
  sourceAddress: string;
  payloadHash: string;
  expressExecutor: string;
}
export type ExpressExecutedEvent = TypedEvent<
  [string, string, string, string, string],
  ExpressExecutedEventObject
>;

export type ExpressExecutedEventFilter = TypedEventFilter<ExpressExecutedEvent>;

export interface ExpressExecutionFulfilledEventObject {
  commandId: string;
  sourceChain: string;
  sourceAddress: string;
  payloadHash: string;
  expressExecutor: string;
}
export type ExpressExecutionFulfilledEvent = TypedEvent<
  [string, string, string, string, string],
  ExpressExecutionFulfilledEventObject
>;

export type ExpressExecutionFulfilledEventFilter =
  TypedEventFilter<ExpressExecutionFulfilledEvent>;

export interface InterchainTokenDeployedEventObject {
  tokenId: string;
  tokenAddress: string;
  minter: string;
  name: string;
  symbol: string;
  decimals: number;
}
export type InterchainTokenDeployedEvent = TypedEvent<
  [string, string, string, string, string, number],
  InterchainTokenDeployedEventObject
>;

export type InterchainTokenDeployedEventFilter =
  TypedEventFilter<InterchainTokenDeployedEvent>;

export interface InterchainTokenDeploymentStartedEventObject {
  tokenId: string;
  tokenName: string;
  tokenSymbol: string;
  tokenDecimals: number;
  minter: string;
  destinationChain: string;
}
export type InterchainTokenDeploymentStartedEvent = TypedEvent<
  [string, string, string, number, string, string],
  InterchainTokenDeploymentStartedEventObject
>;

export type InterchainTokenDeploymentStartedEventFilter =
  TypedEventFilter<InterchainTokenDeploymentStartedEvent>;

export interface InterchainTokenIdClaimedEventObject {
  tokenId: string;
  deployer: string;
  salt: string;
}
export type InterchainTokenIdClaimedEvent = TypedEvent<
  [string, string, string],
  InterchainTokenIdClaimedEventObject
>;

export type InterchainTokenIdClaimedEventFilter =
  TypedEventFilter<InterchainTokenIdClaimedEvent>;

export interface InterchainTransferEventObject {
  tokenId: string;
  sourceAddress: string;
  destinationChain: string;
  destinationAddress: string;
  amount: BigNumber;
  dataHash: string;
}
export type InterchainTransferEvent = TypedEvent<
  [string, string, string, string, BigNumber, string],
  InterchainTransferEventObject
>;

export type InterchainTransferEventFilter =
  TypedEventFilter<InterchainTransferEvent>;

export interface InterchainTransferReceivedEventObject {
  commandId: string;
  tokenId: string;
  sourceChain: string;
  sourceAddress: string;
  destinationAddress: string;
  amount: BigNumber;
  dataHash: string;
}
export type InterchainTransferReceivedEvent = TypedEvent<
  [string, string, string, string, string, BigNumber, string],
  InterchainTransferReceivedEventObject
>;

export type InterchainTransferReceivedEventFilter =
  TypedEventFilter<InterchainTransferReceivedEvent>;

export interface LinkTokenStartedEventObject {
  tokenId: string;
  destinationChain: string;
  sourceTokenAddress: string;
  destinationTokenAddress: string;
  tokenManagerType: number;
  params: string;
}
export type LinkTokenStartedEvent = TypedEvent<
  [string, string, string, string, number, string],
  LinkTokenStartedEventObject
>;

export type LinkTokenStartedEventFilter =
  TypedEventFilter<LinkTokenStartedEvent>;

export interface OwnershipTransferStartedEventObject {
  newOwner: string;
}
export type OwnershipTransferStartedEvent = TypedEvent<
  [string],
  OwnershipTransferStartedEventObject
>;

export type OwnershipTransferStartedEventFilter =
  TypedEventFilter<OwnershipTransferStartedEvent>;

export interface OwnershipTransferredEventObject {
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface RolesAddedEventObject {
  account: string;
  accountRoles: BigNumber;
}
export type RolesAddedEvent = TypedEvent<
  [string, BigNumber],
  RolesAddedEventObject
>;

export type RolesAddedEventFilter = TypedEventFilter<RolesAddedEvent>;

export interface RolesProposedEventObject {
  fromAccount: string;
  toAccount: string;
  accountRoles: BigNumber;
}
export type RolesProposedEvent = TypedEvent<
  [string, string, BigNumber],
  RolesProposedEventObject
>;

export type RolesProposedEventFilter = TypedEventFilter<RolesProposedEvent>;

export interface RolesRemovedEventObject {
  account: string;
  accountRoles: BigNumber;
}
export type RolesRemovedEvent = TypedEvent<
  [string, BigNumber],
  RolesRemovedEventObject
>;

export type RolesRemovedEventFilter = TypedEventFilter<RolesRemovedEvent>;

export interface TokenManagerDeployedEventObject {
  tokenId: string;
  tokenManager: string;
  tokenManagerType: number;
  params: string;
}
export type TokenManagerDeployedEvent = TypedEvent<
  [string, string, number, string],
  TokenManagerDeployedEventObject
>;

export type TokenManagerDeployedEventFilter =
  TypedEventFilter<TokenManagerDeployedEvent>;

export interface TokenMetadataRegisteredEventObject {
  tokenAddress: string;
  decimals: number;
}
export type TokenMetadataRegisteredEvent = TypedEvent<
  [string, number],
  TokenMetadataRegisteredEventObject
>;

export type TokenMetadataRegisteredEventFilter =
  TypedEventFilter<TokenMetadataRegisteredEvent>;

export interface TrustedAddressRemovedEventObject {
  chain: string;
}
export type TrustedAddressRemovedEvent = TypedEvent<
  [string],
  TrustedAddressRemovedEventObject
>;

export type TrustedAddressRemovedEventFilter =
  TypedEventFilter<TrustedAddressRemovedEvent>;

export interface TrustedAddressSetEventObject {
  chain: string;
  address_: string;
}
export type TrustedAddressSetEvent = TypedEvent<
  [string, string],
  TrustedAddressSetEventObject
>;

export type TrustedAddressSetEventFilter =
  TypedEventFilter<TrustedAddressSetEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface UpgradedEventObject {
  newImplementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface InterchainTokenService extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: InterchainTokenServiceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptOperatorship(
      fromOperator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    chainName(
      overrides?: CallOverrides
    ): Promise<[string] & { chainName_: string }>;

    chainNameHash(overrides?: CallOverrides): Promise<[string]>;

    contractCallValue(
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber]>;

    contractId(overrides?: CallOverrides): Promise<[string]>;

    deployInterchainToken(
      salt: PromiseOrValue<BytesLike>,
      destinationChain: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      decimals: PromiseOrValue<BigNumberish>,
      minter: PromiseOrValue<BytesLike>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployedTokenManager(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { tokenManager_: string }>;

    execute(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    expressExecute(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    gasService(overrides?: CallOverrides): Promise<[string]>;

    gateway(overrides?: CallOverrides): Promise<[string]>;

    gatewayCaller(overrides?: CallOverrides): Promise<[string]>;

    getExpressExecutor(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payloadHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { expressExecutor: string }>;

    hasRole(
      account: PromiseOrValue<string>,
      role: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    implementation(
      overrides?: CallOverrides
    ): Promise<[string] & { implementation_: string }>;

    interchainTokenAddress(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { tokenAddress: string }>;

    interchainTokenDeployer(overrides?: CallOverrides): Promise<[string]>;

    interchainTokenFactory(overrides?: CallOverrides): Promise<[string]>;

    interchainTokenId(
      sender: PromiseOrValue<string>,
      salt: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { tokenId: string }>;

    interchainTransfer(
      tokenId: PromiseOrValue<BytesLike>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isOperator(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isTrustedAddress(
      chain: PromiseOrValue<string>,
      address_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    linkToken(
      salt: PromiseOrValue<BytesLike>,
      destinationChain: PromiseOrValue<string>,
      destinationTokenAddress: PromiseOrValue<BytesLike>,
      tokenManagerType: PromiseOrValue<BigNumberish>,
      linkParams: PromiseOrValue<BytesLike>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    migrateInterchainToken(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string] & { owner_: string }>;

    paused(
      overrides?: CallOverrides
    ): Promise<[boolean] & { paused_: boolean }>;

    pendingOwner(
      overrides?: CallOverrides
    ): Promise<[string] & { owner_: string }>;

    proposeOperatorship(
      operator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    proposeOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerCustomToken(
      salt: PromiseOrValue<BytesLike>,
      tokenAddress: PromiseOrValue<string>,
      tokenManagerType: PromiseOrValue<BigNumberish>,
      linkParams: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerTokenMetadata(
      tokenAddress: PromiseOrValue<string>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registeredTokenAddress(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { tokenAddress: string }>;

    removeTrustedAddress(
      chain: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFlowLimits(
      tokenIds: PromiseOrValue<BytesLike>[],
      flowLimits: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPauseStatus(
      paused: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTrustedAddress(
      chain: PromiseOrValue<string>,
      address_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setup(
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tokenHandler(overrides?: CallOverrides): Promise<[string]>;

    tokenManager(overrides?: CallOverrides): Promise<[string]>;

    tokenManagerAddress(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { tokenManagerAddress_: string }>;

    tokenManagerDeployer(overrides?: CallOverrides): Promise<[string]>;

    tokenManagerImplementation(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    transferOperatorship(
      operator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transmitInterchainTransfer(
      tokenId: PromiseOrValue<BytesLike>,
      sourceAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    trustedAddress(
      chain: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string] & { trustedAddress_: string }>;

    trustedAddressHash(
      chain: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string] & { trustedAddressHash_: string }>;

    upgrade(
      newImplementation: PromiseOrValue<string>,
      newImplementationCodeHash: PromiseOrValue<BytesLike>,
      params: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  acceptOperatorship(
    fromOperator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  acceptOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  chainName(overrides?: CallOverrides): Promise<string>;

  chainNameHash(overrides?: CallOverrides): Promise<string>;

  contractCallValue(
    sourceChain: PromiseOrValue<string>,
    sourceAddress: PromiseOrValue<string>,
    payload: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber]>;

  contractId(overrides?: CallOverrides): Promise<string>;

  deployInterchainToken(
    salt: PromiseOrValue<BytesLike>,
    destinationChain: PromiseOrValue<string>,
    name: PromiseOrValue<string>,
    symbol: PromiseOrValue<string>,
    decimals: PromiseOrValue<BigNumberish>,
    minter: PromiseOrValue<BytesLike>,
    gasValue: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployedTokenManager(
    tokenId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  execute(
    commandId: PromiseOrValue<BytesLike>,
    sourceChain: PromiseOrValue<string>,
    sourceAddress: PromiseOrValue<string>,
    payload: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  expressExecute(
    commandId: PromiseOrValue<BytesLike>,
    sourceChain: PromiseOrValue<string>,
    sourceAddress: PromiseOrValue<string>,
    payload: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  gasService(overrides?: CallOverrides): Promise<string>;

  gateway(overrides?: CallOverrides): Promise<string>;

  gatewayCaller(overrides?: CallOverrides): Promise<string>;

  getExpressExecutor(
    commandId: PromiseOrValue<BytesLike>,
    sourceChain: PromiseOrValue<string>,
    sourceAddress: PromiseOrValue<string>,
    payloadHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  hasRole(
    account: PromiseOrValue<string>,
    role: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  implementation(overrides?: CallOverrides): Promise<string>;

  interchainTokenAddress(
    tokenId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  interchainTokenDeployer(overrides?: CallOverrides): Promise<string>;

  interchainTokenFactory(overrides?: CallOverrides): Promise<string>;

  interchainTokenId(
    sender: PromiseOrValue<string>,
    salt: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  interchainTransfer(
    tokenId: PromiseOrValue<BytesLike>,
    destinationChain: PromiseOrValue<string>,
    destinationAddress: PromiseOrValue<BytesLike>,
    amount: PromiseOrValue<BigNumberish>,
    metadata: PromiseOrValue<BytesLike>,
    gasValue: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isOperator(
    addr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isTrustedAddress(
    chain: PromiseOrValue<string>,
    address_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  linkToken(
    salt: PromiseOrValue<BytesLike>,
    destinationChain: PromiseOrValue<string>,
    destinationTokenAddress: PromiseOrValue<BytesLike>,
    tokenManagerType: PromiseOrValue<BigNumberish>,
    linkParams: PromiseOrValue<BytesLike>,
    gasValue: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  migrateInterchainToken(
    tokenId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  multicall(
    data: PromiseOrValue<BytesLike>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  pendingOwner(overrides?: CallOverrides): Promise<string>;

  proposeOperatorship(
    operator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  proposeOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerCustomToken(
    salt: PromiseOrValue<BytesLike>,
    tokenAddress: PromiseOrValue<string>,
    tokenManagerType: PromiseOrValue<BigNumberish>,
    linkParams: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerTokenMetadata(
    tokenAddress: PromiseOrValue<string>,
    gasValue: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registeredTokenAddress(
    tokenId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  removeTrustedAddress(
    chain: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFlowLimits(
    tokenIds: PromiseOrValue<BytesLike>[],
    flowLimits: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPauseStatus(
    paused: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTrustedAddress(
    chain: PromiseOrValue<string>,
    address_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setup(
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tokenHandler(overrides?: CallOverrides): Promise<string>;

  tokenManager(overrides?: CallOverrides): Promise<string>;

  tokenManagerAddress(
    tokenId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  tokenManagerDeployer(overrides?: CallOverrides): Promise<string>;

  tokenManagerImplementation(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  transferOperatorship(
    operator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transmitInterchainTransfer(
    tokenId: PromiseOrValue<BytesLike>,
    sourceAddress: PromiseOrValue<string>,
    destinationChain: PromiseOrValue<string>,
    destinationAddress: PromiseOrValue<BytesLike>,
    amount: PromiseOrValue<BigNumberish>,
    metadata: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  trustedAddress(
    chain: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  trustedAddressHash(
    chain: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  upgrade(
    newImplementation: PromiseOrValue<string>,
    newImplementationCodeHash: PromiseOrValue<BytesLike>,
    params: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptOperatorship(
      fromOperator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    chainName(overrides?: CallOverrides): Promise<string>;

    chainNameHash(overrides?: CallOverrides): Promise<string>;

    contractCallValue(
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber]>;

    contractId(overrides?: CallOverrides): Promise<string>;

    deployInterchainToken(
      salt: PromiseOrValue<BytesLike>,
      destinationChain: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      decimals: PromiseOrValue<BigNumberish>,
      minter: PromiseOrValue<BytesLike>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    deployedTokenManager(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    execute(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    expressExecute(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    gasService(overrides?: CallOverrides): Promise<string>;

    gateway(overrides?: CallOverrides): Promise<string>;

    gatewayCaller(overrides?: CallOverrides): Promise<string>;

    getExpressExecutor(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payloadHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    hasRole(
      account: PromiseOrValue<string>,
      role: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    implementation(overrides?: CallOverrides): Promise<string>;

    interchainTokenAddress(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    interchainTokenDeployer(overrides?: CallOverrides): Promise<string>;

    interchainTokenFactory(overrides?: CallOverrides): Promise<string>;

    interchainTokenId(
      sender: PromiseOrValue<string>,
      salt: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    interchainTransfer(
      tokenId: PromiseOrValue<BytesLike>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    isOperator(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isTrustedAddress(
      chain: PromiseOrValue<string>,
      address_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    linkToken(
      salt: PromiseOrValue<BytesLike>,
      destinationChain: PromiseOrValue<string>,
      destinationTokenAddress: PromiseOrValue<BytesLike>,
      tokenManagerType: PromiseOrValue<BigNumberish>,
      linkParams: PromiseOrValue<BytesLike>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    migrateInterchainToken(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<string[]>;

    owner(overrides?: CallOverrides): Promise<string>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    pendingOwner(overrides?: CallOverrides): Promise<string>;

    proposeOperatorship(
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    proposeOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerCustomToken(
      salt: PromiseOrValue<BytesLike>,
      tokenAddress: PromiseOrValue<string>,
      tokenManagerType: PromiseOrValue<BigNumberish>,
      linkParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    registerTokenMetadata(
      tokenAddress: PromiseOrValue<string>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    registeredTokenAddress(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    removeTrustedAddress(
      chain: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFlowLimits(
      tokenIds: PromiseOrValue<BytesLike>[],
      flowLimits: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    setPauseStatus(
      paused: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setTrustedAddress(
      chain: PromiseOrValue<string>,
      address_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setup(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    tokenHandler(overrides?: CallOverrides): Promise<string>;

    tokenManager(overrides?: CallOverrides): Promise<string>;

    tokenManagerAddress(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    tokenManagerDeployer(overrides?: CallOverrides): Promise<string>;

    tokenManagerImplementation(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    transferOperatorship(
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transmitInterchainTransfer(
      tokenId: PromiseOrValue<BytesLike>,
      sourceAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    trustedAddress(
      chain: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    trustedAddressHash(
      chain: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    upgrade(
      newImplementation: PromiseOrValue<string>,
      newImplementationCodeHash: PromiseOrValue<BytesLike>,
      params: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ExpressExecuted(bytes32,string,string,bytes32,address)"(
      commandId?: PromiseOrValue<BytesLike> | null,
      sourceChain?: null,
      sourceAddress?: null,
      payloadHash?: null,
      expressExecutor?: PromiseOrValue<string> | null
    ): ExpressExecutedEventFilter;
    ExpressExecuted(
      commandId?: PromiseOrValue<BytesLike> | null,
      sourceChain?: null,
      sourceAddress?: null,
      payloadHash?: null,
      expressExecutor?: PromiseOrValue<string> | null
    ): ExpressExecutedEventFilter;

    "ExpressExecutionFulfilled(bytes32,string,string,bytes32,address)"(
      commandId?: PromiseOrValue<BytesLike> | null,
      sourceChain?: null,
      sourceAddress?: null,
      payloadHash?: null,
      expressExecutor?: PromiseOrValue<string> | null
    ): ExpressExecutionFulfilledEventFilter;
    ExpressExecutionFulfilled(
      commandId?: PromiseOrValue<BytesLike> | null,
      sourceChain?: null,
      sourceAddress?: null,
      payloadHash?: null,
      expressExecutor?: PromiseOrValue<string> | null
    ): ExpressExecutionFulfilledEventFilter;

    "InterchainTokenDeployed(bytes32,address,address,string,string,uint8)"(
      tokenId?: PromiseOrValue<BytesLike> | null,
      tokenAddress?: null,
      minter?: PromiseOrValue<string> | null,
      name?: null,
      symbol?: null,
      decimals?: null
    ): InterchainTokenDeployedEventFilter;
    InterchainTokenDeployed(
      tokenId?: PromiseOrValue<BytesLike> | null,
      tokenAddress?: null,
      minter?: PromiseOrValue<string> | null,
      name?: null,
      symbol?: null,
      decimals?: null
    ): InterchainTokenDeployedEventFilter;

    "InterchainTokenDeploymentStarted(bytes32,string,string,uint8,bytes,string)"(
      tokenId?: PromiseOrValue<BytesLike> | null,
      tokenName?: null,
      tokenSymbol?: null,
      tokenDecimals?: null,
      minter?: null,
      destinationChain?: null
    ): InterchainTokenDeploymentStartedEventFilter;
    InterchainTokenDeploymentStarted(
      tokenId?: PromiseOrValue<BytesLike> | null,
      tokenName?: null,
      tokenSymbol?: null,
      tokenDecimals?: null,
      minter?: null,
      destinationChain?: null
    ): InterchainTokenDeploymentStartedEventFilter;

    "InterchainTokenIdClaimed(bytes32,address,bytes32)"(
      tokenId?: PromiseOrValue<BytesLike> | null,
      deployer?: PromiseOrValue<string> | null,
      salt?: PromiseOrValue<BytesLike> | null
    ): InterchainTokenIdClaimedEventFilter;
    InterchainTokenIdClaimed(
      tokenId?: PromiseOrValue<BytesLike> | null,
      deployer?: PromiseOrValue<string> | null,
      salt?: PromiseOrValue<BytesLike> | null
    ): InterchainTokenIdClaimedEventFilter;

    "InterchainTransfer(bytes32,address,string,bytes,uint256,bytes32)"(
      tokenId?: PromiseOrValue<BytesLike> | null,
      sourceAddress?: PromiseOrValue<string> | null,
      destinationChain?: null,
      destinationAddress?: null,
      amount?: null,
      dataHash?: PromiseOrValue<BytesLike> | null
    ): InterchainTransferEventFilter;
    InterchainTransfer(
      tokenId?: PromiseOrValue<BytesLike> | null,
      sourceAddress?: PromiseOrValue<string> | null,
      destinationChain?: null,
      destinationAddress?: null,
      amount?: null,
      dataHash?: PromiseOrValue<BytesLike> | null
    ): InterchainTransferEventFilter;

    "InterchainTransferReceived(bytes32,bytes32,string,bytes,address,uint256,bytes32)"(
      commandId?: PromiseOrValue<BytesLike> | null,
      tokenId?: PromiseOrValue<BytesLike> | null,
      sourceChain?: null,
      sourceAddress?: null,
      destinationAddress?: PromiseOrValue<string> | null,
      amount?: null,
      dataHash?: null
    ): InterchainTransferReceivedEventFilter;
    InterchainTransferReceived(
      commandId?: PromiseOrValue<BytesLike> | null,
      tokenId?: PromiseOrValue<BytesLike> | null,
      sourceChain?: null,
      sourceAddress?: null,
      destinationAddress?: PromiseOrValue<string> | null,
      amount?: null,
      dataHash?: null
    ): InterchainTransferReceivedEventFilter;

    "LinkTokenStarted(bytes32,string,bytes,bytes,uint8,bytes)"(
      tokenId?: PromiseOrValue<BytesLike> | null,
      destinationChain?: null,
      sourceTokenAddress?: null,
      destinationTokenAddress?: null,
      tokenManagerType?: PromiseOrValue<BigNumberish> | null,
      params?: null
    ): LinkTokenStartedEventFilter;
    LinkTokenStarted(
      tokenId?: PromiseOrValue<BytesLike> | null,
      destinationChain?: null,
      sourceTokenAddress?: null,
      destinationTokenAddress?: null,
      tokenManagerType?: PromiseOrValue<BigNumberish> | null,
      params?: null
    ): LinkTokenStartedEventFilter;

    "OwnershipTransferStarted(address)"(
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferStartedEventFilter;
    OwnershipTransferStarted(
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferStartedEventFilter;

    "OwnershipTransferred(address)"(
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(
      account?: PromiseOrValue<string> | null
    ): PausedEventFilter;
    Paused(account?: PromiseOrValue<string> | null): PausedEventFilter;

    "RolesAdded(address,uint256)"(
      account?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesAddedEventFilter;
    RolesAdded(
      account?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesAddedEventFilter;

    "RolesProposed(address,address,uint256)"(
      fromAccount?: PromiseOrValue<string> | null,
      toAccount?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesProposedEventFilter;
    RolesProposed(
      fromAccount?: PromiseOrValue<string> | null,
      toAccount?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesProposedEventFilter;

    "RolesRemoved(address,uint256)"(
      account?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesRemovedEventFilter;
    RolesRemoved(
      account?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesRemovedEventFilter;

    "TokenManagerDeployed(bytes32,address,uint8,bytes)"(
      tokenId?: PromiseOrValue<BytesLike> | null,
      tokenManager?: null,
      tokenManagerType?: PromiseOrValue<BigNumberish> | null,
      params?: null
    ): TokenManagerDeployedEventFilter;
    TokenManagerDeployed(
      tokenId?: PromiseOrValue<BytesLike> | null,
      tokenManager?: null,
      tokenManagerType?: PromiseOrValue<BigNumberish> | null,
      params?: null
    ): TokenManagerDeployedEventFilter;

    "TokenMetadataRegistered(address,uint8)"(
      tokenAddress?: PromiseOrValue<string> | null,
      decimals?: null
    ): TokenMetadataRegisteredEventFilter;
    TokenMetadataRegistered(
      tokenAddress?: PromiseOrValue<string> | null,
      decimals?: null
    ): TokenMetadataRegisteredEventFilter;

    "TrustedAddressRemoved(string)"(
      chain?: null
    ): TrustedAddressRemovedEventFilter;
    TrustedAddressRemoved(chain?: null): TrustedAddressRemovedEventFilter;

    "TrustedAddressSet(string,string)"(
      chain?: null,
      address_?: null
    ): TrustedAddressSetEventFilter;
    TrustedAddressSet(
      chain?: null,
      address_?: null
    ): TrustedAddressSetEventFilter;

    "Unpaused(address)"(
      account?: PromiseOrValue<string> | null
    ): UnpausedEventFilter;
    Unpaused(account?: PromiseOrValue<string> | null): UnpausedEventFilter;

    "Upgraded(address)"(
      newImplementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      newImplementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
  };

  estimateGas: {
    acceptOperatorship(
      fromOperator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    chainName(overrides?: CallOverrides): Promise<BigNumber>;

    chainNameHash(overrides?: CallOverrides): Promise<BigNumber>;

    contractCallValue(
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contractId(overrides?: CallOverrides): Promise<BigNumber>;

    deployInterchainToken(
      salt: PromiseOrValue<BytesLike>,
      destinationChain: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      decimals: PromiseOrValue<BigNumberish>,
      minter: PromiseOrValue<BytesLike>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployedTokenManager(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    execute(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    expressExecute(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    gasService(overrides?: CallOverrides): Promise<BigNumber>;

    gateway(overrides?: CallOverrides): Promise<BigNumber>;

    gatewayCaller(overrides?: CallOverrides): Promise<BigNumber>;

    getExpressExecutor(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payloadHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasRole(
      account: PromiseOrValue<string>,
      role: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    implementation(overrides?: CallOverrides): Promise<BigNumber>;

    interchainTokenAddress(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interchainTokenDeployer(overrides?: CallOverrides): Promise<BigNumber>;

    interchainTokenFactory(overrides?: CallOverrides): Promise<BigNumber>;

    interchainTokenId(
      sender: PromiseOrValue<string>,
      salt: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interchainTransfer(
      tokenId: PromiseOrValue<BytesLike>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isOperator(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isTrustedAddress(
      chain: PromiseOrValue<string>,
      address_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    linkToken(
      salt: PromiseOrValue<BytesLike>,
      destinationChain: PromiseOrValue<string>,
      destinationTokenAddress: PromiseOrValue<BytesLike>,
      tokenManagerType: PromiseOrValue<BigNumberish>,
      linkParams: PromiseOrValue<BytesLike>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    migrateInterchainToken(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    pendingOwner(overrides?: CallOverrides): Promise<BigNumber>;

    proposeOperatorship(
      operator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    proposeOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerCustomToken(
      salt: PromiseOrValue<BytesLike>,
      tokenAddress: PromiseOrValue<string>,
      tokenManagerType: PromiseOrValue<BigNumberish>,
      linkParams: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerTokenMetadata(
      tokenAddress: PromiseOrValue<string>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registeredTokenAddress(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeTrustedAddress(
      chain: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFlowLimits(
      tokenIds: PromiseOrValue<BytesLike>[],
      flowLimits: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPauseStatus(
      paused: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTrustedAddress(
      chain: PromiseOrValue<string>,
      address_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setup(
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tokenHandler(overrides?: CallOverrides): Promise<BigNumber>;

    tokenManager(overrides?: CallOverrides): Promise<BigNumber>;

    tokenManagerAddress(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenManagerDeployer(overrides?: CallOverrides): Promise<BigNumber>;

    tokenManagerImplementation(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOperatorship(
      operator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transmitInterchainTransfer(
      tokenId: PromiseOrValue<BytesLike>,
      sourceAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    trustedAddress(
      chain: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    trustedAddressHash(
      chain: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    upgrade(
      newImplementation: PromiseOrValue<string>,
      newImplementationCodeHash: PromiseOrValue<BytesLike>,
      params: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOperatorship(
      fromOperator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    chainName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    chainNameHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    contractCallValue(
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contractId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deployInterchainToken(
      salt: PromiseOrValue<BytesLike>,
      destinationChain: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      decimals: PromiseOrValue<BigNumberish>,
      minter: PromiseOrValue<BytesLike>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployedTokenManager(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    execute(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    expressExecute(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    gasService(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gateway(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gatewayCaller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getExpressExecutor(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payloadHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasRole(
      account: PromiseOrValue<string>,
      role: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    implementation(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    interchainTokenAddress(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    interchainTokenDeployer(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    interchainTokenFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    interchainTokenId(
      sender: PromiseOrValue<string>,
      salt: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    interchainTransfer(
      tokenId: PromiseOrValue<BytesLike>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isOperator(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isTrustedAddress(
      chain: PromiseOrValue<string>,
      address_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    linkToken(
      salt: PromiseOrValue<BytesLike>,
      destinationChain: PromiseOrValue<string>,
      destinationTokenAddress: PromiseOrValue<BytesLike>,
      tokenManagerType: PromiseOrValue<BigNumberish>,
      linkParams: PromiseOrValue<BytesLike>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    migrateInterchainToken(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proposeOperatorship(
      operator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    proposeOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerCustomToken(
      salt: PromiseOrValue<BytesLike>,
      tokenAddress: PromiseOrValue<string>,
      tokenManagerType: PromiseOrValue<BigNumberish>,
      linkParams: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerTokenMetadata(
      tokenAddress: PromiseOrValue<string>,
      gasValue: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registeredTokenAddress(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeTrustedAddress(
      chain: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFlowLimits(
      tokenIds: PromiseOrValue<BytesLike>[],
      flowLimits: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPauseStatus(
      paused: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTrustedAddress(
      chain: PromiseOrValue<string>,
      address_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setup(
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tokenHandler(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenManagerAddress(
      tokenId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenManagerDeployer(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenManagerImplementation(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOperatorship(
      operator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transmitInterchainTransfer(
      tokenId: PromiseOrValue<BytesLike>,
      sourceAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    trustedAddress(
      chain: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    trustedAddressHash(
      chain: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    upgrade(
      newImplementation: PromiseOrValue<string>,
      newImplementationCodeHash: PromiseOrValue<BytesLike>,
      params: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
