/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface BaseWeightedMultisigInterface extends utils.Interface {
  functions: {
    "domainSeparator()": FunctionFragment;
    "epoch()": FunctionFragment;
    "epochBySignersHash(bytes32)": FunctionFragment;
    "lastRotationTimestamp()": FunctionFragment;
    "messageHashToSign(bytes32,bytes32)": FunctionFragment;
    "minimumRotationDelay()": FunctionFragment;
    "previousSignersRetention()": FunctionFragment;
    "signersHashByEpoch(uint256)": FunctionFragment;
    "timeSinceRotation()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "domainSeparator"
      | "epoch"
      | "epochBySignersHash"
      | "lastRotationTimestamp"
      | "messageHashToSign"
      | "minimumRotationDelay"
      | "previousSignersRetention"
      | "signersHashByEpoch"
      | "timeSinceRotation"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "domainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "epoch", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "epochBySignersHash",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "lastRotationTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "messageHashToSign",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "minimumRotationDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "previousSignersRetention",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "signersHashByEpoch",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "timeSinceRotation",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "domainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "epoch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "epochBySignersHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRotationTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "messageHashToSign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumRotationDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previousSignersRetention",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signersHashByEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeSinceRotation",
    data: BytesLike
  ): Result;

  events: {
    "SignersRotated(uint256,bytes32,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SignersRotated"): EventFragment;
}

export interface SignersRotatedEventObject {
  epoch: BigNumber;
  signersHash: string;
  signers: string;
}
export type SignersRotatedEvent = TypedEvent<
  [BigNumber, string, string],
  SignersRotatedEventObject
>;

export type SignersRotatedEventFilter = TypedEventFilter<SignersRotatedEvent>;

export interface BaseWeightedMultisig extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BaseWeightedMultisigInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    domainSeparator(overrides?: CallOverrides): Promise<[string]>;

    epoch(overrides?: CallOverrides): Promise<[BigNumber]>;

    epochBySignersHash(
      signersHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    lastRotationTimestamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    messageHashToSign(
      signersHash: PromiseOrValue<BytesLike>,
      dataHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    minimumRotationDelay(overrides?: CallOverrides): Promise<[BigNumber]>;

    previousSignersRetention(overrides?: CallOverrides): Promise<[BigNumber]>;

    signersHashByEpoch(
      signerEpoch: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    timeSinceRotation(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  domainSeparator(overrides?: CallOverrides): Promise<string>;

  epoch(overrides?: CallOverrides): Promise<BigNumber>;

  epochBySignersHash(
    signersHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  lastRotationTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  messageHashToSign(
    signersHash: PromiseOrValue<BytesLike>,
    dataHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  minimumRotationDelay(overrides?: CallOverrides): Promise<BigNumber>;

  previousSignersRetention(overrides?: CallOverrides): Promise<BigNumber>;

  signersHashByEpoch(
    signerEpoch: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  timeSinceRotation(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    domainSeparator(overrides?: CallOverrides): Promise<string>;

    epoch(overrides?: CallOverrides): Promise<BigNumber>;

    epochBySignersHash(
      signersHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastRotationTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    messageHashToSign(
      signersHash: PromiseOrValue<BytesLike>,
      dataHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    minimumRotationDelay(overrides?: CallOverrides): Promise<BigNumber>;

    previousSignersRetention(overrides?: CallOverrides): Promise<BigNumber>;

    signersHashByEpoch(
      signerEpoch: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    timeSinceRotation(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "SignersRotated(uint256,bytes32,bytes)"(
      epoch?: PromiseOrValue<BigNumberish> | null,
      signersHash?: PromiseOrValue<BytesLike> | null,
      signers?: null
    ): SignersRotatedEventFilter;
    SignersRotated(
      epoch?: PromiseOrValue<BigNumberish> | null,
      signersHash?: PromiseOrValue<BytesLike> | null,
      signers?: null
    ): SignersRotatedEventFilter;
  };

  estimateGas: {
    domainSeparator(overrides?: CallOverrides): Promise<BigNumber>;

    epoch(overrides?: CallOverrides): Promise<BigNumber>;

    epochBySignersHash(
      signersHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastRotationTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    messageHashToSign(
      signersHash: PromiseOrValue<BytesLike>,
      dataHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    minimumRotationDelay(overrides?: CallOverrides): Promise<BigNumber>;

    previousSignersRetention(overrides?: CallOverrides): Promise<BigNumber>;

    signersHashByEpoch(
      signerEpoch: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    timeSinceRotation(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    domainSeparator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    epoch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    epochBySignersHash(
      signersHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastRotationTimestamp(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    messageHashToSign(
      signersHash: PromiseOrValue<BytesLike>,
      dataHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minimumRotationDelay(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    previousSignersRetention(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    signersHashByEpoch(
      signerEpoch: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    timeSinceRotation(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
