/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AxelarServiceGovernance } from "./AxelarServiceGovernance";
export type { BaseMultisig } from "./BaseMultisig";
export type { BaseWeightedMultisig } from "./BaseWeightedMultisig";
export type { InterchainGovernance } from "./InterchainGovernance";
export type { InterchainMultisig } from "./InterchainMultisig";
export type { Multisig } from "./Multisig";
