/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IInterchainTransferReceived } from "./IInterchainTransferReceived";
export type { IInterchainTransferSent } from "./IInterchainTransferSent";
