/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  BaseWeightedMultisig,
  BaseWeightedMultisigInterface,
} from "../../../../axelar-gmp-sdk-solidity/contracts/governance/BaseWeightedMultisig";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "signersHash",
        type: "bytes32",
      },
    ],
    name: "DuplicateSigners",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "minimumRotationDelay",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lastRotationTimestamp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "timeElapsed",
        type: "uint256",
      },
    ],
    name: "InsufficientRotationDelay",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidSigners",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidThreshold",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidWeights",
    type: "error",
  },
  {
    inputs: [],
    name: "LowSignaturesWeight",
    type: "error",
  },
  {
    inputs: [],
    name: "MalformedSignatures",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "required",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "provided",
        type: "uint256",
      },
    ],
    name: "RedundantSignaturesProvided",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "signersHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "signers",
        type: "bytes",
      },
    ],
    name: "SignersRotated",
    type: "event",
  },
  {
    inputs: [],
    name: "domainSeparator",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "epoch",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "signersHash",
        type: "bytes32",
      },
    ],
    name: "epochBySignersHash",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lastRotationTimestamp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "signersHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "dataHash",
        type: "bytes32",
      },
    ],
    name: "messageHashToSign",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minimumRotationDelay",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "previousSignersRetention",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "signerEpoch",
        type: "uint256",
      },
    ],
    name: "signersHashByEpoch",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "timeSinceRotation",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class BaseWeightedMultisig__factory {
  static readonly abi = _abi;
  static createInterface(): BaseWeightedMultisigInterface {
    return new utils.Interface(_abi) as BaseWeightedMultisigInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BaseWeightedMultisig {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as BaseWeightedMultisig;
  }
}
