/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAxelarAmplifierGatewayAuth,
  IAxelarAmplifierGatewayAuthInterface,
} from "../../../../axelar-gmp-sdk-solidity/contracts/interfaces/IAxelarAmplifierGatewayAuth";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "signer",
                type: "address",
              },
              {
                internalType: "uint128",
                name: "weight",
                type: "uint128",
              },
            ],
            internalType: "struct WeightedSigner[]",
            name: "signers",
            type: "tuple[]",
          },
          {
            internalType: "uint128",
            name: "threshold",
            type: "uint128",
          },
          {
            internalType: "bytes32",
            name: "nonce",
            type: "bytes32",
          },
        ],
        internalType: "struct WeightedSigners",
        name: "newSigners",
        type: "tuple",
      },
    ],
    name: "rotateSigners",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "dataHash",
        type: "bytes32",
      },
      {
        components: [
          {
            components: [
              {
                components: [
                  {
                    internalType: "address",
                    name: "signer",
                    type: "address",
                  },
                  {
                    internalType: "uint128",
                    name: "weight",
                    type: "uint128",
                  },
                ],
                internalType: "struct WeightedSigner[]",
                name: "signers",
                type: "tuple[]",
              },
              {
                internalType: "uint128",
                name: "threshold",
                type: "uint128",
              },
              {
                internalType: "bytes32",
                name: "nonce",
                type: "bytes32",
              },
            ],
            internalType: "struct WeightedSigners",
            name: "signers",
            type: "tuple",
          },
          {
            internalType: "bytes[]",
            name: "signatures",
            type: "bytes[]",
          },
        ],
        internalType: "struct Proof",
        name: "proof",
        type: "tuple",
      },
    ],
    name: "validateProof",
    outputs: [
      {
        internalType: "bool",
        name: "isLatestSigners",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAxelarAmplifierGatewayAuth__factory {
  static readonly abi = _abi;
  static createInterface(): IAxelarAmplifierGatewayAuthInterface {
    return new utils.Interface(_abi) as IAxelarAmplifierGatewayAuthInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAxelarAmplifierGatewayAuth {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IAxelarAmplifierGatewayAuth;
  }
}
