/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IReentrancyGuard,
  IReentrancyGuardInterface,
} from "../../../../axelar-gmp-sdk-solidity/contracts/interfaces/IReentrancyGuard";

const _abi = [
  {
    inputs: [],
    name: "ReentrantCall",
    type: "error",
  },
] as const;

export class IReentrancyGuard__factory {
  static readonly abi = _abi;
  static createInterface(): IReentrancyGuardInterface {
    return new utils.Interface(_abi) as IReentrancyGuardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IReentrancyGuard {
    return new Contract(address, _abi, signerOrProvider) as IReentrancyGuard;
  }
}
