/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC20BurnFrom,
  IERC20BurnFromInterface,
} from "../../../../axelar-cgp-solidity/contracts/interfaces/IERC20BurnFrom";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burnFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC20BurnFrom__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20BurnFromInterface {
    return new utils.Interface(_abi) as IERC20BurnFromInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20BurnFrom {
    return new Contract(address, _abi, signerOrProvider) as IERC20BurnFrom;
  }
}
