/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAddressTracker,
  IAddressTrackerInterface,
} from "../../../../interchain-token-service/contracts/interfaces/IAddressTracker";

const _abi = [
  {
    inputs: [],
    name: "LengthMismatch",
    type: "error",
  },
  {
    inputs: [],
    name: "UntrustedChain",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroStringLength",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "chain",
        type: "string",
      },
    ],
    name: "TrustedAddressRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "chain",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "address_",
        type: "string",
      },
    ],
    name: "TrustedAddressSet",
    type: "event",
  },
  {
    inputs: [],
    name: "chainName",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "chain",
        type: "string",
      },
      {
        internalType: "string",
        name: "address_",
        type: "string",
      },
    ],
    name: "isTrustedAddress",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "chain",
        type: "string",
      },
    ],
    name: "removeTrustedAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "chain",
        type: "string",
      },
      {
        internalType: "string",
        name: "address_",
        type: "string",
      },
    ],
    name: "setTrustedAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "chain",
        type: "string",
      },
    ],
    name: "trustedAddress",
    outputs: [
      {
        internalType: "string",
        name: "trustedAddress_",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "chain",
        type: "string",
      },
    ],
    name: "trustedAddressHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "trustedAddressHash_",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAddressTracker__factory {
  static readonly abi = _abi;
  static createInterface(): IAddressTrackerInterface {
    return new utils.Interface(_abi) as IAddressTrackerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAddressTracker {
    return new Contract(address, _abi, signerOrProvider) as IAddressTracker;
  }
}
