/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBaseTokenManager,
  IBaseTokenManagerInterface,
} from "../../../../interchain-token-service/contracts/interfaces/IBaseTokenManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "params",
        type: "bytes",
      },
    ],
    name: "getTokenAddressFromParams",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "interchainTokenId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tokenAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBaseTokenManager__factory {
  static readonly abi = _abi;
  static createInterface(): IBaseTokenManagerInterface {
    return new utils.Interface(_abi) as IBaseTokenManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBaseTokenManager {
    return new Contract(address, _abi, signerOrProvider) as IBaseTokenManager;
  }
}
