/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC20BurnableFrom,
  IERC20BurnableFromInterface,
} from "../../../../interchain-token-service/contracts/interfaces/IERC20BurnableFrom";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burnFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC20BurnableFrom__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20BurnableFromInterface {
    return new utils.Interface(_abi) as IERC20BurnableFromInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20BurnableFrom {
    return new Contract(address, _abi, signerOrProvider) as IERC20BurnableFrom;
  }
}
