/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFlowLimit,
  IFlowLimitInterface,
} from "../../../../interchain-token-service/contracts/interfaces/IFlowLimit";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "flowAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "flowToAdd",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenManager",
        type: "address",
      },
    ],
    name: "FlowAdditionOverflow",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "flowAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenManager",
        type: "address",
      },
    ],
    name: "FlowLimitExceeded",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "flowLimit",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "flowToCompare",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenManager",
        type: "address",
      },
    ],
    name: "FlowLimitOverflow",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "tokenId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "flowLimit_",
        type: "uint256",
      },
    ],
    name: "FlowLimitSet",
    type: "event",
  },
  {
    inputs: [],
    name: "flowInAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "flowInAmount_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "flowLimit",
    outputs: [
      {
        internalType: "uint256",
        name: "flowLimit_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "flowOutAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "flowOutAmount_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFlowLimit__factory {
  static readonly abi = _abi;
  static createInterface(): IFlowLimitInterface {
    return new utils.Interface(_abi) as IFlowLimitInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFlowLimit {
    return new Contract(address, _abi, signerOrProvider) as IFlowLimit;
  }
}
