/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGatewayCaller,
  IGatewayCallerInterface,
} from "../../../../interchain-token-service/contracts/interfaces/IGatewayCaller";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "metadataVersion",
        type: "uint32",
      },
    ],
    name: "InvalidMetadataVersion",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "destinationChain",
        type: "string",
      },
      {
        internalType: "string",
        name: "destinationAddress",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
      {
        internalType: "enum IGatewayCaller.MetadataVersion",
        name: "metadataVersion",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "gasValue",
        type: "uint256",
      },
    ],
    name: "callContract",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IGatewayCaller__factory {
  static readonly abi = _abi;
  static createInterface(): IGatewayCallerInterface {
    return new utils.Interface(_abi) as IGatewayCallerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGatewayCaller {
    return new Contract(address, _abi, signerOrProvider) as IGatewayCaller;
  }
}
