/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IInterchainTokenExpressExecutable,
  IInterchainTokenExpressExecutableInterface,
} from "../../../../interchain-token-service/contracts/interfaces/IInterchainTokenExpressExecutable";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "commandId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "sourceChain",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "sourceAddress",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "tokenId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "executeWithInterchainToken",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "commandId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "sourceChain",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "sourceAddress",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "tokenId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "expressExecuteWithInterchainToken",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IInterchainTokenExpressExecutable__factory {
  static readonly abi = _abi;
  static createInterface(): IInterchainTokenExpressExecutableInterface {
    return new utils.Interface(
      _abi
    ) as IInterchainTokenExpressExecutableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInterchainTokenExpressExecutable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IInterchainTokenExpressExecutable;
  }
}
