/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITokenManagerDeployer,
  ITokenManagerDeployerInterface,
} from "../../../../interchain-token-service/contracts/interfaces/ITokenManagerDeployer";

const _abi = [
  {
    inputs: [],
    name: "TokenManagerDeploymentFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "tokenId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "implementationType",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "params",
        type: "bytes",
      },
    ],
    name: "deployTokenManager",
    outputs: [
      {
        internalType: "address",
        name: "tokenManager",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ITokenManagerDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenManagerDeployerInterface {
    return new utils.Interface(_abi) as ITokenManagerDeployerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenManagerDeployer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITokenManagerDeployer;
  }
}
