/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITransmitInterchainToken,
  ITransmitInterchainTokenInterface,
} from "../../../../interchain-token-service/contracts/interfaces/ITransmitInterchainToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "tokenId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "sourceAddress",
        type: "address",
      },
      {
        internalType: "string",
        name: "destinationChain",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "destinationAddress",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "metadata",
        type: "bytes",
      },
    ],
    name: "transmitInterchainTransfer",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ITransmitInterchainToken__factory {
  static readonly abi = _abi;
  static createInterface(): ITransmitInterchainTokenInterface {
    return new utils.Interface(_abi) as ITransmitInterchainTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITransmitInterchainToken {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITransmitInterchainToken;
  }
}
