/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface IInterchainTokenStandardInterface extends utils.Interface {
  functions: {
    "interchainTransfer(string,bytes,uint256,bytes)": FunctionFragment;
    "interchainTransferFrom(address,string,bytes,uint256,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "interchainTransfer" | "interchainTransferFrom"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "interchainTransfer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "interchainTransferFrom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "interchainTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interchainTransferFrom",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IInterchainTokenStandard extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IInterchainTokenStandardInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    interchainTransfer(
      destinationChain: PromiseOrValue<string>,
      recipient: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    interchainTransferFrom(
      sender: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      recipient: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  interchainTransfer(
    destinationChain: PromiseOrValue<string>,
    recipient: PromiseOrValue<BytesLike>,
    amount: PromiseOrValue<BigNumberish>,
    metadata: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  interchainTransferFrom(
    sender: PromiseOrValue<string>,
    destinationChain: PromiseOrValue<string>,
    recipient: PromiseOrValue<BytesLike>,
    amount: PromiseOrValue<BigNumberish>,
    metadata: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    interchainTransfer(
      destinationChain: PromiseOrValue<string>,
      recipient: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    interchainTransferFrom(
      sender: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      recipient: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    interchainTransfer(
      destinationChain: PromiseOrValue<string>,
      recipient: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    interchainTransferFrom(
      sender: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      recipient: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    interchainTransfer(
      destinationChain: PromiseOrValue<string>,
      recipient: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    interchainTransferFrom(
      sender: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      recipient: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
