/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface IMinterInterface extends utils.Interface {
  functions: {
    "acceptMintership(address)": FunctionFragment;
    "hasRole(address,uint8)": FunctionFragment;
    "isMinter(address)": FunctionFragment;
    "proposeMintership(address)": FunctionFragment;
    "transferMintership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptMintership"
      | "hasRole"
      | "isMinter"
      | "proposeMintership"
      | "transferMintership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptMintership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isMinter",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeMintership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferMintership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptMintership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMinter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeMintership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferMintership",
    data: BytesLike
  ): Result;

  events: {
    "RolesAdded(address,uint256)": EventFragment;
    "RolesProposed(address,address,uint256)": EventFragment;
    "RolesRemoved(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RolesAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RolesProposed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RolesRemoved"): EventFragment;
}

export interface RolesAddedEventObject {
  account: string;
  accountRoles: BigNumber;
}
export type RolesAddedEvent = TypedEvent<
  [string, BigNumber],
  RolesAddedEventObject
>;

export type RolesAddedEventFilter = TypedEventFilter<RolesAddedEvent>;

export interface RolesProposedEventObject {
  fromAccount: string;
  toAccount: string;
  accountRoles: BigNumber;
}
export type RolesProposedEvent = TypedEvent<
  [string, string, BigNumber],
  RolesProposedEventObject
>;

export type RolesProposedEventFilter = TypedEventFilter<RolesProposedEvent>;

export interface RolesRemovedEventObject {
  account: string;
  accountRoles: BigNumber;
}
export type RolesRemovedEvent = TypedEvent<
  [string, BigNumber],
  RolesRemovedEventObject
>;

export type RolesRemovedEventFilter = TypedEventFilter<RolesRemovedEvent>;

export interface IMinter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMinterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptMintership(
      fromMinter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      account: PromiseOrValue<string>,
      role: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isMinter(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    proposeMintership(
      minter_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferMintership(
      minter_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  acceptMintership(
    fromMinter: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    account: PromiseOrValue<string>,
    role: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isMinter(
    addr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  proposeMintership(
    minter_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferMintership(
    minter_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptMintership(
      fromMinter: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      account: PromiseOrValue<string>,
      role: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isMinter(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    proposeMintership(
      minter_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferMintership(
      minter_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "RolesAdded(address,uint256)"(
      account?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesAddedEventFilter;
    RolesAdded(
      account?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesAddedEventFilter;

    "RolesProposed(address,address,uint256)"(
      fromAccount?: PromiseOrValue<string> | null,
      toAccount?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesProposedEventFilter;
    RolesProposed(
      fromAccount?: PromiseOrValue<string> | null,
      toAccount?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesProposedEventFilter;

    "RolesRemoved(address,uint256)"(
      account?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesRemovedEventFilter;
    RolesRemoved(
      account?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesRemovedEventFilter;
  };

  estimateGas: {
    acceptMintership(
      fromMinter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hasRole(
      account: PromiseOrValue<string>,
      role: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isMinter(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposeMintership(
      minter_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferMintership(
      minter_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptMintership(
      fromMinter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      account: PromiseOrValue<string>,
      role: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isMinter(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposeMintership(
      minter_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferMintership(
      minter_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
