/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface ITransmitInterchainTokenInterface extends utils.Interface {
  functions: {
    "transmitInterchainTransfer(bytes32,address,string,bytes,uint256,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "transmitInterchainTransfer"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "transmitInterchainTransfer",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "transmitInterchainTransfer",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ITransmitInterchainToken extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITransmitInterchainTokenInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    transmitInterchainTransfer(
      tokenId: PromiseOrValue<BytesLike>,
      sourceAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  transmitInterchainTransfer(
    tokenId: PromiseOrValue<BytesLike>,
    sourceAddress: PromiseOrValue<string>,
    destinationChain: PromiseOrValue<string>,
    destinationAddress: PromiseOrValue<BytesLike>,
    amount: PromiseOrValue<BigNumberish>,
    metadata: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    transmitInterchainTransfer(
      tokenId: PromiseOrValue<BytesLike>,
      sourceAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    transmitInterchainTransfer(
      tokenId: PromiseOrValue<BytesLike>,
      sourceAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    transmitInterchainTransfer(
      tokenId: PromiseOrValue<BytesLike>,
      sourceAddress: PromiseOrValue<string>,
      destinationChain: PromiseOrValue<string>,
      destinationAddress: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      metadata: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
