/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export type WeightedSignerStruct = {
  signer: PromiseOrValue<string>;
  weight: PromiseOrValue<BigNumberish>;
};

export type WeightedSignerStructOutput = [string, BigNumber] & {
  signer: string;
  weight: BigNumber;
};

export type WeightedSignersStruct = {
  signers: WeightedSignerStruct[];
  threshold: PromiseOrValue<BigNumberish>;
  nonce: PromiseOrValue<BytesLike>;
};

export type WeightedSignersStructOutput = [
  WeightedSignerStructOutput[],
  BigNumber,
  string
] & {
  signers: WeightedSignerStructOutput[];
  threshold: BigNumber;
  nonce: string;
};

export type ProofStruct = {
  signers: WeightedSignersStruct;
  signatures: PromiseOrValue<BytesLike>[];
};

export type ProofStructOutput = [WeightedSignersStructOutput, string[]] & {
  signers: WeightedSignersStructOutput;
  signatures: string[];
};

export interface IAxelarAmplifierGatewayAuthInterface extends utils.Interface {
  functions: {
    "rotateSigners(((address,uint128)[],uint128,bytes32))": FunctionFragment;
    "validateProof(bytes32,(((address,uint128)[],uint128,bytes32),bytes[]))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "rotateSigners" | "validateProof"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "rotateSigners",
    values: [WeightedSignersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "validateProof",
    values: [PromiseOrValue<BytesLike>, ProofStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "rotateSigners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateProof",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IAxelarAmplifierGatewayAuth extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAxelarAmplifierGatewayAuthInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    rotateSigners(
      newSigners: WeightedSignersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    validateProof(
      dataHash: PromiseOrValue<BytesLike>,
      proof: ProofStruct,
      overrides?: CallOverrides
    ): Promise<[boolean] & { isLatestSigners: boolean }>;
  };

  rotateSigners(
    newSigners: WeightedSignersStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  validateProof(
    dataHash: PromiseOrValue<BytesLike>,
    proof: ProofStruct,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    rotateSigners(
      newSigners: WeightedSignersStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    validateProof(
      dataHash: PromiseOrValue<BytesLike>,
      proof: ProofStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    rotateSigners(
      newSigners: WeightedSignersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    validateProof(
      dataHash: PromiseOrValue<BytesLike>,
      proof: ProofStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    rotateSigners(
      newSigners: WeightedSignersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    validateProof(
      dataHash: PromiseOrValue<BytesLike>,
      proof: ProofStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
