/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface IInterchainGovernanceInterface extends utils.Interface {
  functions: {
    "execute(bytes32,string,string,bytes)": FunctionFragment;
    "executeProposal(address,bytes,uint256)": FunctionFragment;
    "gateway()": FunctionFragment;
    "getProposalEta(address,bytes,uint256)": FunctionFragment;
    "getTimeLock(bytes32)": FunctionFragment;
    "governanceAddress()": FunctionFragment;
    "governanceAddressHash()": FunctionFragment;
    "governanceChain()": FunctionFragment;
    "governanceChainHash()": FunctionFragment;
    "minimumTimeLockDelay()": FunctionFragment;
    "withdraw(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "execute"
      | "executeProposal"
      | "gateway"
      | "getProposalEta"
      | "getTimeLock"
      | "governanceAddress"
      | "governanceAddressHash"
      | "governanceChain"
      | "governanceChainHash"
      | "minimumTimeLockDelay"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "execute",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "gateway", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getProposalEta",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeLock",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "governanceAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceAddressHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceChain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceChainHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumTimeLockDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gateway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProposalEta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceAddressHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceChainHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumTimeLockDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "ProposalCancelled(bytes32,address,bytes,uint256,uint256)": EventFragment;
    "ProposalExecuted(bytes32,address,bytes,uint256,uint256)": EventFragment;
    "ProposalScheduled(bytes32,address,bytes,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProposalCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalScheduled"): EventFragment;
}

export interface ProposalCancelledEventObject {
  proposalHash: string;
  target: string;
  callData: string;
  value: BigNumber;
  eta: BigNumber;
}
export type ProposalCancelledEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  ProposalCancelledEventObject
>;

export type ProposalCancelledEventFilter =
  TypedEventFilter<ProposalCancelledEvent>;

export interface ProposalExecutedEventObject {
  proposalHash: string;
  target: string;
  callData: string;
  value: BigNumber;
  timestamp: BigNumber;
}
export type ProposalExecutedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  ProposalExecutedEventObject
>;

export type ProposalExecutedEventFilter =
  TypedEventFilter<ProposalExecutedEvent>;

export interface ProposalScheduledEventObject {
  proposalHash: string;
  target: string;
  callData: string;
  value: BigNumber;
  eta: BigNumber;
}
export type ProposalScheduledEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  ProposalScheduledEventObject
>;

export type ProposalScheduledEventFilter =
  TypedEventFilter<ProposalScheduledEvent>;

export interface IInterchainGovernance extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IInterchainGovernanceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    execute(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeProposal(
      targetContract: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    gateway(overrides?: CallOverrides): Promise<[string]>;

    getProposalEta(
      target: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      nativeValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTimeLock(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    governanceAddress(overrides?: CallOverrides): Promise<[string]>;

    governanceAddressHash(overrides?: CallOverrides): Promise<[string]>;

    governanceChain(overrides?: CallOverrides): Promise<[string]>;

    governanceChainHash(overrides?: CallOverrides): Promise<[string]>;

    minimumTimeLockDelay(overrides?: CallOverrides): Promise<[BigNumber]>;

    withdraw(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  execute(
    commandId: PromiseOrValue<BytesLike>,
    sourceChain: PromiseOrValue<string>,
    sourceAddress: PromiseOrValue<string>,
    payload: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeProposal(
    targetContract: PromiseOrValue<string>,
    callData: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  gateway(overrides?: CallOverrides): Promise<string>;

  getProposalEta(
    target: PromiseOrValue<string>,
    callData: PromiseOrValue<BytesLike>,
    nativeValue: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTimeLock(
    hash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  governanceAddress(overrides?: CallOverrides): Promise<string>;

  governanceAddressHash(overrides?: CallOverrides): Promise<string>;

  governanceChain(overrides?: CallOverrides): Promise<string>;

  governanceChainHash(overrides?: CallOverrides): Promise<string>;

  minimumTimeLockDelay(overrides?: CallOverrides): Promise<BigNumber>;

  withdraw(
    recipient: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    execute(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    executeProposal(
      targetContract: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    gateway(overrides?: CallOverrides): Promise<string>;

    getProposalEta(
      target: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      nativeValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTimeLock(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    governanceAddress(overrides?: CallOverrides): Promise<string>;

    governanceAddressHash(overrides?: CallOverrides): Promise<string>;

    governanceChain(overrides?: CallOverrides): Promise<string>;

    governanceChainHash(overrides?: CallOverrides): Promise<string>;

    minimumTimeLockDelay(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ProposalCancelled(bytes32,address,bytes,uint256,uint256)"(
      proposalHash?: PromiseOrValue<BytesLike> | null,
      target?: PromiseOrValue<string> | null,
      callData?: null,
      value?: null,
      eta?: PromiseOrValue<BigNumberish> | null
    ): ProposalCancelledEventFilter;
    ProposalCancelled(
      proposalHash?: PromiseOrValue<BytesLike> | null,
      target?: PromiseOrValue<string> | null,
      callData?: null,
      value?: null,
      eta?: PromiseOrValue<BigNumberish> | null
    ): ProposalCancelledEventFilter;

    "ProposalExecuted(bytes32,address,bytes,uint256,uint256)"(
      proposalHash?: PromiseOrValue<BytesLike> | null,
      target?: PromiseOrValue<string> | null,
      callData?: null,
      value?: null,
      timestamp?: PromiseOrValue<BigNumberish> | null
    ): ProposalExecutedEventFilter;
    ProposalExecuted(
      proposalHash?: PromiseOrValue<BytesLike> | null,
      target?: PromiseOrValue<string> | null,
      callData?: null,
      value?: null,
      timestamp?: PromiseOrValue<BigNumberish> | null
    ): ProposalExecutedEventFilter;

    "ProposalScheduled(bytes32,address,bytes,uint256,uint256)"(
      proposalHash?: PromiseOrValue<BytesLike> | null,
      target?: PromiseOrValue<string> | null,
      callData?: null,
      value?: null,
      eta?: PromiseOrValue<BigNumberish> | null
    ): ProposalScheduledEventFilter;
    ProposalScheduled(
      proposalHash?: PromiseOrValue<BytesLike> | null,
      target?: PromiseOrValue<string> | null,
      callData?: null,
      value?: null,
      eta?: PromiseOrValue<BigNumberish> | null
    ): ProposalScheduledEventFilter;
  };

  estimateGas: {
    execute(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeProposal(
      targetContract: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    gateway(overrides?: CallOverrides): Promise<BigNumber>;

    getProposalEta(
      target: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      nativeValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTimeLock(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    governanceAddress(overrides?: CallOverrides): Promise<BigNumber>;

    governanceAddressHash(overrides?: CallOverrides): Promise<BigNumber>;

    governanceChain(overrides?: CallOverrides): Promise<BigNumber>;

    governanceChainHash(overrides?: CallOverrides): Promise<BigNumber>;

    minimumTimeLockDelay(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    execute(
      commandId: PromiseOrValue<BytesLike>,
      sourceChain: PromiseOrValue<string>,
      sourceAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeProposal(
      targetContract: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    gateway(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getProposalEta(
      target: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      nativeValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTimeLock(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    governanceAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governanceAddressHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    governanceChain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governanceChainHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minimumTimeLockDelay(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
