/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type {
  FixedProxy,
  FixedProxyInterface,
} from "../../../../axelar-gmp-sdk-solidity/contracts/upgradable/FixedProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "implementationAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "AlreadyInitialized",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidImplementation",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidOwner",
    type: "error",
  },
  {
    inputs: [],
    name: "NotOwner",
    type: "error",
  },
  {
    inputs: [],
    name: "SetupFailed",
    type: "error",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "setupParams",
        type: "bytes",
      },
    ],
    name: "setup",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161022238038061022283398101604081905261002f91610040565b6001600160a01b0316608052610070565b60006020828403121561005257600080fd5b81516001600160a01b038116811461006957600080fd5b9392505050565b6080516101926100906000396000818160360152608d01526101926000f3fe60806040526004361061002d5760003560e01c80635c60da1b1461007b5780639ded06df146100cb57610034565b3661003457005b7f00000000000000000000000000000000000000000000000000000000000000003660008037600080366000845af43d6000803e808015610074573d6000f35b3d6000fd5b005b34801561008757600080fd5b506100af7f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b03909116815260200160405180910390f35b3480156100d757600080fd5b506100796100e63660046100ea565b5050565b600080602083850312156100fd57600080fd5b823567ffffffffffffffff8082111561011557600080fd5b818501915085601f83011261012957600080fd5b81358181111561013857600080fd5b86602082850101111561014a57600080fd5b6020929092019691955090935050505056fea264697066735822122032baee47c8e531352ba4177e6625326f4614b2cbd35fc55004452922f10529a164736f6c63430008170033";

type FixedProxyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FixedProxyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FixedProxy__factory extends ContractFactory {
  constructor(...args: FixedProxyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    implementationAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<FixedProxy> {
    return super.deploy(
      implementationAddress,
      overrides || {}
    ) as Promise<FixedProxy>;
  }
  override getDeployTransaction(
    implementationAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(implementationAddress, overrides || {});
  }
  override attach(address: string): FixedProxy {
    return super.attach(address) as FixedProxy;
  }
  override connect(signer: Signer): FixedProxy__factory {
    return super.connect(signer) as FixedProxy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FixedProxyInterface {
    return new utils.Interface(_abi) as FixedProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FixedProxy {
    return new Contract(address, _abi, signerOrProvider) as FixedProxy;
  }
}
