/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface RolesBaseInterface extends utils.Interface {
  functions: {
    "hasRole(address,uint8)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "hasRole"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;

  events: {
    "RolesAdded(address,uint256)": EventFragment;
    "RolesProposed(address,address,uint256)": EventFragment;
    "RolesRemoved(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RolesAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RolesProposed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RolesRemoved"): EventFragment;
}

export interface RolesAddedEventObject {
  account: string;
  accountRoles: BigNumber;
}
export type RolesAddedEvent = TypedEvent<
  [string, BigNumber],
  RolesAddedEventObject
>;

export type RolesAddedEventFilter = TypedEventFilter<RolesAddedEvent>;

export interface RolesProposedEventObject {
  fromAccount: string;
  toAccount: string;
  accountRoles: BigNumber;
}
export type RolesProposedEvent = TypedEvent<
  [string, string, BigNumber],
  RolesProposedEventObject
>;

export type RolesProposedEventFilter = TypedEventFilter<RolesProposedEvent>;

export interface RolesRemovedEventObject {
  account: string;
  accountRoles: BigNumber;
}
export type RolesRemovedEvent = TypedEvent<
  [string, BigNumber],
  RolesRemovedEventObject
>;

export type RolesRemovedEventFilter = TypedEventFilter<RolesRemovedEvent>;

export interface RolesBase extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RolesBaseInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    hasRole(
      account: PromiseOrValue<string>,
      role: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  hasRole(
    account: PromiseOrValue<string>,
    role: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    hasRole(
      account: PromiseOrValue<string>,
      role: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "RolesAdded(address,uint256)"(
      account?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesAddedEventFilter;
    RolesAdded(
      account?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesAddedEventFilter;

    "RolesProposed(address,address,uint256)"(
      fromAccount?: PromiseOrValue<string> | null,
      toAccount?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesProposedEventFilter;
    RolesProposed(
      fromAccount?: PromiseOrValue<string> | null,
      toAccount?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesProposedEventFilter;

    "RolesRemoved(address,uint256)"(
      account?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesRemovedEventFilter;
    RolesRemoved(
      account?: PromiseOrValue<string> | null,
      accountRoles?: null
    ): RolesRemovedEventFilter;
  };

  estimateGas: {
    hasRole(
      account: PromiseOrValue<string>,
      role: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    hasRole(
      account: PromiseOrValue<string>,
      role: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
