/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface Create2DeployerInterface extends utils.Interface {
  functions: {
    "deploy(bytes,bytes32)": FunctionFragment;
    "deployAndInit(bytes,bytes32,bytes)": FunctionFragment;
    "deployedAddress(bytes,address,bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "deploy" | "deployAndInit" | "deployedAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deploy",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "deployAndInit",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedAddress",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployAndInit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedAddress",
    data: BytesLike
  ): Result;

  events: {
    "Deployed(address,address,bytes32,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Deployed"): EventFragment;
}

export interface DeployedEventObject {
  deployedAddress: string;
  sender: string;
  salt: string;
  bytecodeHash: string;
}
export type DeployedEvent = TypedEvent<
  [string, string, string, string],
  DeployedEventObject
>;

export type DeployedEventFilter = TypedEventFilter<DeployedEvent>;

export interface Create2Deployer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Create2DeployerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deploy(
      bytecode: PromiseOrValue<BytesLike>,
      salt: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployAndInit(
      bytecode: PromiseOrValue<BytesLike>,
      salt: PromiseOrValue<BytesLike>,
      init: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployedAddress(
      bytecode: PromiseOrValue<BytesLike>,
      sender: PromiseOrValue<string>,
      salt: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  deploy(
    bytecode: PromiseOrValue<BytesLike>,
    salt: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployAndInit(
    bytecode: PromiseOrValue<BytesLike>,
    salt: PromiseOrValue<BytesLike>,
    init: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployedAddress(
    bytecode: PromiseOrValue<BytesLike>,
    sender: PromiseOrValue<string>,
    salt: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    deploy(
      bytecode: PromiseOrValue<BytesLike>,
      salt: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    deployAndInit(
      bytecode: PromiseOrValue<BytesLike>,
      salt: PromiseOrValue<BytesLike>,
      init: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    deployedAddress(
      bytecode: PromiseOrValue<BytesLike>,
      sender: PromiseOrValue<string>,
      salt: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "Deployed(address,address,bytes32,bytes32)"(
      deployedAddress?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null,
      salt?: PromiseOrValue<BytesLike> | null,
      bytecodeHash?: null
    ): DeployedEventFilter;
    Deployed(
      deployedAddress?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null,
      salt?: PromiseOrValue<BytesLike> | null,
      bytecodeHash?: null
    ): DeployedEventFilter;
  };

  estimateGas: {
    deploy(
      bytecode: PromiseOrValue<BytesLike>,
      salt: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployAndInit(
      bytecode: PromiseOrValue<BytesLike>,
      salt: PromiseOrValue<BytesLike>,
      init: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployedAddress(
      bytecode: PromiseOrValue<BytesLike>,
      sender: PromiseOrValue<string>,
      salt: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deploy(
      bytecode: PromiseOrValue<BytesLike>,
      salt: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployAndInit(
      bytecode: PromiseOrValue<BytesLike>,
      salt: PromiseOrValue<BytesLike>,
      init: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployedAddress(
      bytecode: PromiseOrValue<BytesLike>,
      sender: PromiseOrValue<string>,
      salt: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
