/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AxelarAmplifierGateway } from "./AxelarAmplifierGateway";
export type { AxelarAmplifierGatewayProxy } from "./AxelarAmplifierGatewayProxy";
export type { BaseAmplifierGateway } from "./BaseAmplifierGateway";
